name = "StringiFor"
version = "1.1.4"
author = "Stefano Zaghi"
copyright = "Copyright © 2016, Stefano Zaghi"
license = "Multiple licenses"
description = "Strings Fortran Manipulator with steroids"
maintainer = "Stefano Zaghi"
homepage = "https://github.com/szaghi/StringiFor"

[library]
source-dir = "src/lib"

[install]
library = true

[dependencies]
[dependencies.BeFoR64]
git = "https://github.com/szaghi/BeFoR64"
rev = "09b95c08a2ee8995d19cf8551c22b783193f6246"

[dependencies.FACE]
git = "https://github.com/szaghi/FACE"
rev = "1455c549ae0c1ead96961ca61a73131d8176b6a4"

[dependencies.PENF]
git = "https://github.com/szaghi/PENF"
rev = "65061235982495b158412b70c05b228af4320d94"
