bit_size – StringiFor
bit_size Interface
Source File
public interface bit_size
Overloading of the intrinsic bit_size function for computing the number of bits of (also) real and character variables.
Calls
Module Procedures
private elemental function bit_size_R8P(i) result(bits)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: i
Real variable whose number of bits must be computed.
Return Value integer(kind=I1P)
Number of bits of r.
Description
Compute the number of bits of a real variable.
private elemental function bit_size_R4P(i) result(bits)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: i
Real variable whose number of bits must be computed.
Return Value integer(kind=I1P)
Number of bits of r.
Description
Compute the number of bits of a real variable.
private elemental function bit_size_chr(i) result(bits)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: i
Character variable whose number of bits must be computed.
Return Value integer(kind=I4P)
Number of bits of c.
Description
Compute the number of bits of a character variable.
Call graph
bit_size calls bit_size_r4p, bit_size_r8p, bit_size_chr