str – StringiFor
str Interface
Source File
public interface str
Convert number (real and integer) to string (number to string type casting).
Calls
Called By
Module Procedures
private elemental function strf_R8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R8P), intent(in) :: n
Real to be converted.
Return Value character(len=DR8P)
Returned string containing input number.
Description
Convert real to string.
private elemental function str_R8P(n, no_sign, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR8P)
Returned string containing input number.
Description
Convert real to string.
private elemental function strf_R4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
real(kind=R4P), intent(in) :: n
Real to be converted.
Return Value character(len=DR4P)
Returned string containing input number.
Description
Convert real to string.
private elemental function str_R4P(n, no_sign, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n
Real to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=DR4P)
Returned string containing input number.
Description
Convert real to string.
private elemental function strf_I8P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I8P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI8P)
Returned string containing input number.
Description
Convert integer to string.
private elemental function str_I8P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI8P)
Returned string containing input number plus padding zeros.
Description
Convert integer to string.
private elemental function strf_I4P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I4P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI4P)
Returned string containing input number.
Description
Convert integer to string.
private elemental function str_I4P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI4P)
Returned string containing input number plus padding zeros.
Description
Converting integer to string.
private elemental function strf_I2P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I2P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI2P)
Returned string containing input number.
Description
Convert integer to string.
private elemental function str_I2P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI2P)
Returned string containing input number plus padding zeros.
Description
Convert integer to string.
private elemental function strf_I1P(fm, n) result(str)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fm
Format different from the standard for the kind.
integer(kind=I1P), intent(in) :: n
Integer to be converted.
Return Value character(len=DI1P)
Returned string containing input number.
Description
Convert integer to string.
private elemental function str_I1P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI1P)
Returned string containing input number plus padding zeros.
Description
Convert integer to string.
private elemental function str_bol(n) result(str)
Arguments
Type Intent Optional Attributes Name
logical, intent(in) :: n
Logical to be converted.
Return Value character(len=1)
Returned string containing input number plus padding zeros.
Description
Convert logical to string.
private pure function str_a_R8P(n, no_sign, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R8P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert real array to string.
private pure function str_a_R4P(n, no_sign, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert real array to string.
private pure function str_a_I8P(n, no_sign, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert integer array to string.
private pure function str_a_I4P(n, no_sign, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I4P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert integer array to string.
private pure function str_a_I2P(n, no_sign, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert integer array to string.
private pure function str_a_I1P(n, no_sign, delimiters) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I1P), intent(in) :: n(:)
Integer array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert integer array to string.
Call graph
str calls str_a_i1p, strf_r8p, str_bol, str_a_r8p, strf_i1p, str_a_i4p, str_i2p, strf_i8p, strf_i4p, str_r4p, str_i1p, str_i4p, str_a_i2p, strf_i2p, str_a_i8p, str_r8p, str_a_r4p, str_i8p, strf_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
bctor_r8p calls str
test_all calls str, bcton
string_assign_real_r16p calls str
bctor_r4p calls str
compact_real calls str
bctoi_i4p calls str
autotest calls str
string_assign_integer_i2p calls str
string_assign_real_r8p calls str
string_assign_real_r4p calls str
string_assign_integer_i4p calls str
bctoi_i8p calls str
string_assign_integer_i8p calls str
bctor_r16p calls str
bctoi_i1p calls str
bctoi_i2p calls str
string_assign_integer_i1p calls str
bcton calls bctor_r8p, bctor_r4p, bctoi_i4p, bctoi_i8p, bctoi_i1p, bctoi_i2p
test_driver calls autotest