Test_Driver – StringiFor
Test_Driver Program
Source File
Uses:
befor64
Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
Usage
 ./Test_Driver
Calls
Source Code
program Test_Driver
!-----------------------------------------------------------------------------------------------------------------------------------
!< Testing program for BeFoR64, Base64 encoding/decoding library for FoRtran poor men
!<
!<### Usage
!<```bash
!< ./Test_Driver
!<```
!-----------------------------------------------------------------------------------------------------------------------------------
use befor64, only : autotest ! Autotesting procedure.
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
implicit none
!-----------------------------------------------------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------------------------------------------------
print "(A)", 'Testing BeFoR64'
call autotest
stop
!-----------------------------------------------------------------------------------------------------------------------------------
endprogram Test_Driver
Call graph
test_driver calls autotest
autotest calls str, b64_init, b64_decode, b64_encode
str calls str_a_i1p, strf_r8p, str_bol, str_a_r8p, strf_i1p, str_a_i4p, str_i2p, strf_i8p, strf_i4p, str_r4p, str_i1p, str_i4p, str_a_i2p, strf_i2p, str_a_i8p, str_r8p, str_a_r4p, str_i8p, strf_r4p
b64_decode calls b64_decode_i8, b64_decode_i1_a, b64_decode_i8_a, b64_decode_i4, b64_decode_r8_a, b64_decode_r4_a, b64_decode_string, b64_decode_i1, b64_decode_r4, b64_decode_i4_a, b64_decode_string_a, b64_decode_i2, b64_decode_i2_a, b64_decode_r8
b64_encode calls b64_encode_i8, b64_encode_r4, b64_encode_r8, b64_encode_string_a, b64_encode_i1_a, b64_encode_i8_a, b64_encode_r8_a, b64_encode_i4_a, b64_encode_r4_a, b64_encode_i2, b64_encode_i1, b64_encode_i4, b64_encode_string, b64_encode_i2_a
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
b64_decode_i8 calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_i1 calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_i4_a calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
b64_decode_i2 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_r8 calls decode_bits
byte_size calls byte_size_i1p, byte_size_r8p, byte_size_i4p, byte_size_i2p, byte_size_i8p, byte_size_r4p, byte_size_chr
b64_encode_i8 calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_r8 calls encode_bits
b64_encode_string_a calls byte_size, encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i2 calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_i2_a calls encode_bits