b64_decode_up – StringiFor
b64_decode_up Subroutine
Source File
public subroutine b64_decode_up(code, up)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: code
Encoded scalar.
class(*), intent(out) :: up
Unlimited polymorphic variable to be decoded.
Description
Decode an unlimited polymorphic scalar from base64.
Calls
Source Code
  subroutine b64_decode_up(code, up)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Decode an unlimited polymorphic scalar from base64.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in)  :: code !< Encoded scalar.
  class(*),     intent(out) :: up   !< Unlimited polymorphic variable to be decoded.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(up)
  type is(real(R8P))
    call b64_decode_R8(code=code,n=up)
  type is(real(R4P))
    call b64_decode_R4(code=code,n=up)
  type is(integer(I8P))
    call b64_decode_I8(code=code,n=up)
  type is(integer(I4P))
    call b64_decode_I4(code=code,n=up)
  type is(integer(I2P))
    call b64_decode_I2(code=code,n=up)
  type is(integer(I1P))
    call b64_decode_I1(code=code,n=up)
  type is(character(*))
    call b64_decode_string(code=code,s=up)
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_decode_up
Call graph
b64_decode_up calls b64_decode_i8, b64_decode_string, b64_decode_r8, b64_decode_i4, b64_decode_i2, b64_decode_r4, b64_decode_i1
b64_decode_i8 calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_r8 calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_r4 calls decode_bits
b64_decode_i1 calls decode_bits
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr