bctoi_I2P – StringiFor
bctoi_I2P Function
Source File
private elemental function bctoi_I2P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
integer(kind=I2P), intent(in) :: knd
Number kind.
Return Value integer(kind=I2P)
Number returned.
Description
Convert bit-string to integer.
Calls
Called By
Source Code
  elemental function bctoi_I2P(bstr, knd) result(n)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert bit-string to integer.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in) :: bstr !< String containing input number.
  integer(I2P), intent(in) :: knd  !< Number kind.
  integer(I2P)             :: n    !< Number returned.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  read(bstr,'(B'//trim(str(bit_size(knd), .true.))//'.'//trim(str(bit_size(knd), .true.))//')') n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction bctoi_I2P
Call graph
bctoi_i2p calls str
str calls strf_i2p, str_i4p, str_a_r4p, strf_i1p, strf_i8p, str_a_i4p, str_a_i8p, str_r8p, str_bol, strf_r4p, strf_i4p, str_a_i2p, str_i2p, str_a_r8p, str_r4p, str_a_i1p, str_i8p, str_i1p, strf_r8p
str_a_r4p calls str_r4p
str_a_i4p calls str_i4p
str_a_i8p calls str_i8p
str_a_i2p calls str_i2p
str_a_r8p calls str_r8p
str_a_i1p calls str_i1p
bcton calls bctoi_i2p