bctor_R4P – StringiFor
bctor_R4P Function
Source File
private elemental function bctor_R4P(bstr, knd) result(n)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: bstr
String containing input number.
real(kind=R4P), intent(in) :: knd
Number kind.
Return Value real(kind=R4P)
Number returned.
Description
Convert bit-string to real.
Calls
Called By
Source Code
  elemental function bctor_R4P(bstr, knd) result(n)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert bit-string to real.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*), intent(in) :: bstr !< String containing input number.
  real(R4P),    intent(in) :: knd  !< Number kind.
  real(R4P)                :: n    !< Number returned.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  read(bstr,'(B'//trim(str(bit_size(knd), .true.))//'.'//trim(str(bit_size(knd), .true.))//')') n
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction bctor_R4P
Call graph
bctor_r4p calls str
str calls str_a_i1p, strf_r8p, str_bol, str_a_r8p, strf_i1p, str_a_i4p, str_i2p, strf_i8p, strf_i4p, str_r4p, str_i1p, str_i4p, str_a_i2p, strf_i2p, str_a_i8p, str_r8p, str_a_r4p, str_i8p, strf_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p
bcton calls bctor_r4p
test_all calls bcton