byte_size_I2P – StringiFor
byte_size_I2P Function
Source File
private elemental function byte_size_I2P(i) result(bytes)
Arguments
Type Intent Optional Attributes Name
integer(kind=I2P), intent(in) :: i
Integer variable whose number of bytes must be computed.
Return Value integer(kind=I1P)
Number of bytes of i.
Description
Compute the number of bytes of an integer variable.
Called By
Source Code
  elemental function byte_size_I2P(i) result(bytes)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Compute the number of bytes of an integer variable.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I2P), intent(in) :: i     !< Integer variable whose number of bytes must be computed.
  integer(I1P)             :: bytes !< Number of bytes of i.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  bytes = bit_size(i)/8_I1P
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction byte_size_I2P
Call graph
byte_size calls byte_size_i2p
b64_encode_string_a calls byte_size
b64_decode_string_a calls byte_size
b64_decode_string calls byte_size
b64_encode_string calls byte_size
b64_encode_up_a calls b64_encode_string_a
b64_encode_up calls b64_encode_up_a, b64_encode_up, b64_encode_string
b64_encode calls b64_encode_string_a, b64_encode_string
autotest calls b64_encode, b64_decode
b64_decode_up_a calls b64_decode_string_a
b64_decode_up calls b64_decode_up_a, b64_decode_up, b64_decode_string
b64_decode calls b64_decode_string_a, b64_decode_string
decode calls b64_decode
test_driver calls autotest
encode calls b64_encode