capitalize – StringiFor
capitalize Function
10 statements
Source File
private elemental function capitalize(self) result(capitalized)
Return a string with its first character capitalized and the rest lowercased.
 type(string) :: astring
 astring = 'say all Hello WorLD!'
 print '(L1)', astring%capitalize()//''=='Say all hello world!'
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
Return Value type(string)
Upper case string.
Calls
Called by
Source Code
   elemental function capitalize(self) result(capitalized)
   !< Return a string with its first character capitalized and the rest lowercased.
   !<
   !<```fortran
   !< type(string) :: astring
   !< astring = 'say all Hello WorLD!'
   !< print '(L1)', astring%capitalize()//''=='Say all hello world!'
   !<```
   !=> T <<<
   class(string), intent(in) :: self        !< The string.
   type(string)              :: capitalized !< Upper case string.
   integer                   :: c           !< Character counter.
   if (allocated(self%raw)) then
     capitalized = self%lower()
     c = index(LOWER_ALPHABET, capitalized%raw(1:1))
     if (c>0) capitalized%raw(1:1) = UPPER_ALPHABET(c:c)
   endif
   endfunction capitalize
Call graph
capitalize calls lower
camelcase calls capitalize
startcase calls capitalize
volatile_doctest calls capitalize, startcase, camelcase