chars – StringiFor
chars Function
9 statements
Source File
private pure function chars(self) result(raw)
Return the raw characters data.
 type(string) :: astring
 astring = 'say all Hello WorLD!'
 print '(L1)', astring%chars()=='say all Hello WorLD!'
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
Return Value character(kind=CK, len=:), allocatable
Raw characters data.
Called by
Source Code
   pure function chars(self) result(raw)
   !< Return the raw characters data.
   !<
   !<```fortran
   !< type(string) :: astring
   !< astring = 'say all Hello WorLD!'
   !< print '(L1)', astring%chars()=='say all Hello WorLD!'
   !<```
   !=> T <<<
   class(string), intent(in)              :: self !< The string.
   character(kind=CK, len=:), allocatable :: raw  !< Raw characters data.
   if (allocated(self%raw)) then
     raw = self%raw
   else
     raw = ''
   endif
   endfunction chars
Call graph
colorize_str calls chars
glob_character calls chars, glob
read_file calls chars, read_lines
read_line calls chars
read_lines calls chars, read_line
write_file calls chars, write_lines
write_line calls chars
volatile_doctest calls chars, read_file, read_lines, read_line, write_file, glob, colorize
glob calls glob_character, glob_string
glob_string calls read_file
write_lines calls write_line
stringifor_test_csv_naive_parser calls read_file, write_file
stringifor_test_parse_large_csv calls read_file