decode – StringiFor
decode Function
Source File
private elemental function decode(self, codec) result(decoded)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
character(kind=CK,len=*), intent(in) :: codec
Encoding codec.
Return Value type(string)
Decoded string.
Description
Return a string decoded accordingly the codec.
Note
Only BASE64 codec is currently available.
Example
```fortran type(string) :: astring astring = 'SG93IGFyZSB5b3U/' print '(A)', astring%decode(codec='base64')//'' ! print "How are you?"
Calls
Variables
Type Visibility Attributes Name Initial
type(string), public :: codec_u
Encoding codec in upper case string.
Source Code
  elemental function decode(self, codec) result(decoded)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Return a string decoded accordingly the codec.
  !<
  !< @note Only BASE64 codec is currently available.
  !<
  !<### Example
  !<
  !<```fortran
  !< type(string) :: astring
  !< astring = 'SG93IGFyZSB5b3U/'
  !< print '(A)', astring%decode(codec='base64')//'' ! print "How are you?"
  !---------------------------------------------------------------------------------------------------------------------------------
  class(string),             intent(in) :: self    !< The string.
  character(kind=CK, len=*), intent(in) :: codec   !< Encoding codec.
  type(string)                          :: decoded !< Decoded string.
  type(string)                          :: codec_u !< Encoding codec in upper case string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (allocated(self%raw)) then
    decoded = self
    codec_u = codec
    select case(codec_u%upper()//'')
    case('BASE64')
      call b64_decode(code=self%raw, s=decoded%raw)
    endselect
    decoded = decoded%strip(remove_nulls=.true.)
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction decode
Call graph
decode calls b64_decode
b64_decode calls b64_decode_i4_a, b64_decode_r8, b64_decode_i1, b64_decode_r8_a, b64_decode_string, b64_decode_r4, b64_decode_i2_a, b64_decode_r4_a, b64_decode_i8, b64_decode_i2, b64_decode_i8_a, b64_decode_i4, b64_decode_i1_a, b64_decode_string_a
b64_decode_i4_a calls decode_bits
b64_decode_r8 calls decode_bits
b64_decode_i1 calls decode_bits
b64_decode_r8_a calls decode_bits
b64_decode_string calls decode_bits, byte_size
b64_decode_r4 calls decode_bits
b64_decode_i2_a calls decode_bits
b64_decode_r4_a calls decode_bits
b64_decode_i8 calls decode_bits
b64_decode_i2 calls decode_bits
b64_decode_i8_a calls decode_bits
b64_decode_i4 calls decode_bits
b64_decode_i1_a calls decode_bits
b64_decode_string_a calls decode_bits, byte_size
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr