encode – StringiFor
encode Function
Source File
private elemental function encode(self, codec) result(encoded)
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
character(kind=CK,len=*), intent(in) :: codec
Encoding codec.
Return Value type(string)
Encoded string.
Description
Return a string encoded accordingly the codec.
Note
Only BASE64 codec is currently available.
Example
```fortran type(string) :: astring astring = 'How are you?' print '(A)', astring%encode(codec='base64')//'' ! print "SG93IGFyZSB5b3U/"
Calls
Source Code
  elemental function encode(self, codec) result(encoded)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Return a string encoded accordingly the codec.
  !<
  !< @note Only BASE64 codec is currently available.
  !<
  !<### Example
  !<
  !<```fortran
  !< type(string) :: astring
  !< astring = 'How are you?'
  !< print '(A)', astring%encode(codec='base64')//'' ! print "SG93IGFyZSB5b3U/"
  !---------------------------------------------------------------------------------------------------------------------------------
  class(string),             intent(in) :: self    !< The string.
  character(kind=CK, len=*), intent(in) :: codec   !< Encoding codec.
  type(string)                          :: encoded !< Encoded string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  if (allocated(self%raw)) then
    encoded = codec
    select case(encoded%upper()//'')
    case('BASE64')
      call b64_encode(s=self%raw, code=encoded%raw)
    endselect
  endif
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction encode
Call graph
encode calls b64_encode
b64_encode calls b64_encode_string_a, b64_encode_r8, b64_encode_i1, b64_encode_i4_a, b64_encode_i1_a, b64_encode_r4_a, b64_encode_r4, b64_encode_i8, b64_encode_string, b64_encode_i2, b64_encode_r8_a, b64_encode_i2_a, b64_encode_i4, b64_encode_i8_a
b64_encode_string_a calls byte_size, encode_bits
b64_encode_r8 calls encode_bits
b64_encode_i1 calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_r4 calls encode_bits
b64_encode_i8 calls encode_bits
b64_encode_string calls byte_size, encode_bits
b64_encode_i2 calls encode_bits
b64_encode_r8_a calls encode_bits
b64_encode_i2_a calls encode_bits
b64_encode_i4 calls encode_bits
b64_encode_i8_a calls encode_bits
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr