replace_one_occurrence – StringiFor
replace_one_occurrence Function
18 statements
Source File
private elemental function replace_one_occurrence(self, old, new) result(replaced)
Return a string with the first occurrence of substring old replaced by new.
Note
The doctest is not necessary, this being tested by replace.
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
character(kind=CK, len=*), intent(in) :: old
Old substring.
character(kind=CK, len=*), intent(in) :: new
New substring.
Return Value type(string)
The string with old replaced by new.
Called by
Source Code
   elemental function replace_one_occurrence(self, old, new) result(replaced)
   !< Return a string with the first occurrence of substring old replaced by new.
   !<
   !< @note The doctest is not necessary, this being tested by [[string:replace]].
   class(string),             intent(in)  :: self      !< The string.
   character(kind=CK, len=*), intent(in)  :: old       !< Old substring.
   character(kind=CK, len=*), intent(in)  :: new       !< New substring.
   type(string)                           :: replaced  !< The string with old replaced by new.
   integer                                :: pos       !< Position from which replace old.
   if (allocated(self%raw)) then
      replaced = self
      pos = index(string=self%raw, substring=old)
      if (pos>0) then
         if (pos==1) then
            replaced%raw = new//self%raw(len(old)+1:)
         else
            replaced%raw = self%raw(1:pos-1)//new//self%raw(pos+len(old):)
         endif
      endif
   endif
   endfunction replace_one_occurrence
Call graph
replace calls replace_one_occurrence
unique calls replace
volatile_doctest calls replace, unique, split, write_file, snakecase, startcase, split_chunked, camelcase, glob
split calls unique
camelcase calls split
glob_string calls split
snakecase calls split
split_chunked calls split
startcase calls split
write_lines calls split
stringifor_test_csv_naive_parser calls split
stringifor_test_parse_large_csv calls split, split_chunked
glob calls glob_string, glob_character
write_file calls write_lines
glob_character calls glob