string_assign_integer_I1P – StringiFor
string_assign_integer_I1P Subroutine
Source File
private elemental subroutine string_assign_integer_I1P(lhs, rhs)
Arguments
Type Intent Optional Attributes Name
class(string), intent(inout) :: lhs
Left hand side.
integer(kind=I1P), intent(in) :: rhs
Right hand side.
Description
Assignment operator from real input.
Calls
Source Code
  elemental subroutine string_assign_integer_I1P(lhs, rhs)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Assignment operator from real input.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(string), intent(inout) :: lhs !< Left hand side.
  integer(I1P),  intent(in)    :: rhs !< Right hand side.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  lhs%raw = trim(str(rhs))
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine string_assign_integer_I1P
Call graph
string_assign_integer_i1p calls str
str calls str_a_i1p, strf_r8p, str_bol, str_a_r8p, strf_i1p, str_a_i4p, str_i2p, strf_i8p, strf_i4p, str_r4p, str_i1p, str_i4p, str_a_i2p, strf_i2p, str_a_i8p, str_r8p, str_a_r4p, str_i8p, strf_r4p
str_a_i1p calls str_i1p
str_a_r8p calls str_r8p
str_a_i4p calls str_i4p
str_r4p calls compact_real_string
str_a_i2p calls str_i2p
str_a_i8p calls str_i8p
str_r8p calls compact_real_string
str_a_r4p calls str_r4p