upper – StringiFor
upper Function
13 statements
Source File
private elemental function upper(self)
Return a string with all uppercase characters.
 type(string) :: astring
 logical      :: test_passed(1)
 astring = 'Hello WorLD!'
 test_passed(1) = astring%upper()//''=='HELLO WORLD!'
 print '(L1)', all(test_passed)
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
Return Value type(string)
Upper case string.
Called by
Source Code
   elemental function upper(self)
   !< Return a string with all uppercase characters.
   !<
   !<```fortran
   !< type(string) :: astring
   !< logical      :: test_passed(1)
   !< astring = 'Hello WorLD!'
   !< test_passed(1) = astring%upper()//''=='HELLO WORLD!'
   !< print '(L1)', all(test_passed)
   !<```
   !=> T <<<
   class(string), intent(in) :: self  !< The string.
   type(string)              :: upper !< Upper case string.
   integer                   :: n1    !< Characters counter.
   integer                   :: n2    !< Characters counter.
   if (allocated(self%raw)) then
      upper = self
      do n1=1, len(self%raw)
         n2 = index(LOWER_ALPHABET, self%raw(n1:n1))
         if (n2>0) upper%raw(n1:n1) = UPPER_ALPHABET(n2:n2)
      enddo
   endif
   endfunction upper
Call graph
decode calls upper
encode calls upper
read_file calls upper, read_lines
read_line calls upper
read_lines calls upper, read_line
write_file calls upper, write_lines
write_line calls upper
volatile_doctest calls upper, read_line, decode, read_file, write_file, encode, read_lines, glob
glob_string calls read_file
write_lines calls write_line
stringifor_test_csv_naive_parser calls read_file, write_file
stringifor_test_parse_large_csv calls read_file
glob calls glob_string, glob_character
glob_character calls glob