write_lines – StringiFor
write_lines Subroutine
15 statements
Source File
private subroutine write_lines(self, unit, form, iostat, iomsg)
Write lines (records) to a connected unit.
This method checks if self contains more than one line (records) and writes them as lines (records).
Note
If the connected unit is unformatted a new_line() character is added at the end (if necessary) to mark the end of line.
Note
There is no doctests, this being tested by means of write_file doctests.
Type Bound
string
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
integer, intent(in) :: unit
Logical unit.
character(len=*), intent(in), optional :: form
Format of unit.
integer, intent(out), optional :: iostat
IO status code.
character(len=*), intent(inout), optional :: iomsg
IO status message.
Calls
Called by
Contents
Source Code
write_lines
Source Code
   subroutine write_lines(self, unit, form, iostat, iomsg)
   !< Write lines (records) to a connected unit.
   !<
   !< This method checks if self contains more than one line (records) and writes them as lines (records).
   !<
   !< @note If the connected unit is unformatted a `new_line()` character is added at the end (if necessary) to mark the end of line.
   !<
   !< @note There is no doctests, this being tested by means of [[string:write_file]] doctests.
   class(string),    intent(in)              :: self     !< The string.
   integer,          intent(in)              :: unit     !< Logical unit.
   character(len=*), intent(in),    optional :: form     !< Format of unit.
   integer,          intent(out),   optional :: iostat   !< IO status code.
   character(len=*), intent(inout), optional :: iomsg    !< IO status message.
   type(string), allocatable                 :: lines(:) !< Lines.
   integer                                   :: l        !< Counter.
   if (allocated(self%raw)) then
      call self%split(tokens=lines, sep=new_line('a'))
      do l=1, size(lines, dim=1)
         call lines(l)%write_line(unit=unit, form=form, iostat=iostat, iomsg=iomsg)
      enddo
   endif
   endsubroutine write_lines
Call graph
write_lines calls split
split calls partition, unique
partition calls raw
unique calls replace
replace calls replace_one_occurrence
write_file calls write_lines