b64_encode_up – StringiFor
b64_encode_up Interface
Source File
public interface b64_encode_up
Encode unlimited polymorphic variable to base64.
This is an interface for encoding both scalar and array.
Warning
The encoded string is returned as varying length character string, character(len=:), allocatable:: string, thus the compiler must support such a Fortran (2003) feature.
Note
Before start to encode anything the library must be initialized. The procedure b64_init must be called at first. The global variable is_b64_initialized can be used to check the status of the initialization.
Usage
For a practical example see the autotest procedure.
Scalar encoding
character(len=:), allocatable:: code64 ! base64 encoded string
...
call b64_encode_up(up=12._R8P,code=code64)
Array encoding
character(len=:), allocatable:: code64 ! base64 encoded string
...
call b64_encode_up(up=[12_I4P,1_I4P],code=code64)
Note
If you want to encode heterogenous data (e.g. integer and real numbers), you must use the auxiliary pack_data procedure.
Warning
The encoding of array of strings is admitted only if each string of the array has the same length.
Calls
Module Procedures
public interface b64_encode_up()
Arguments
None
Description
Encode unlimited polymorphic variable to base64.
private pure subroutine b64_encode_up_a(up, code)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: up(1:)
Unlimited polymorphic variable to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
Description
Encode an unlimited polymorphic array to base64.
Call graph
b64_encode_up calls b64_encode_up, b64_encode_up_a
b64_encode_up_a calls b64_encode_i2_a, b64_encode_i1_a, b64_encode_r4_a, b64_encode_string_a, b64_encode_i8_a, b64_encode_i4_a, b64_encode_r8_a
b64_encode_i2_a calls encode_bits
b64_encode_i1_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_i8_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_r8_a calls encode_bits
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr