glob – StringiFor
glob Interface
3 statements
Source File
public interface glob
Overloading glob procedure.
 type(string)                  :: astring
 character(len=:), allocatable :: alist_chr(:)
 type(string),     allocatable :: alist_str(:)
 integer, parameter            :: Nf=5
 character(14)                 :: files(1:Nf)
 integer                       :: file_unit
 integer                       :: f
 integer                       :: ff
 logical                       :: test_passed
 do f=1, Nf
    files(f) = astring%tempname(prefix='foo-')
    open(newunit=file_unit, file=files(f))
    write(file_unit, *)f
    close(unit=file_unit)
 enddo
 call glob(self=astring, pattern='foo-*', list=alist_chr)
 call glob(self=astring, pattern='foo-*', list=alist_str)
 do f=1, Nf
    open(newunit=file_unit, file=files(f))
    close(unit=file_unit, status='delete')
 enddo
 test_passed = .false.
 outer_chr: do f=1, size(alist_chr, dim=1)
    do ff=1, Nf
       test_passed = alist_chr(f) == files(ff)
       if (test_passed) cycle outer_chr
    enddo
 enddo outer_chr
 if (test_passed) then
    test_passed = .false.
    outer_str: do f=1, size(alist_str, dim=1)
       do ff=1, Nf
          test_passed = alist_str(f) == files(ff)
          if (test_passed) cycle outer_str
       enddo
    enddo outer_str
 endif
 print '(L1)', test_passed
Calls
Called by
Contents
Module Procedures
glob_character glob_string
Module Procedures
private subroutine glob_character(self, pattern, list)
Glob search (character output), finds all the pathnames matching a given pattern according to the rules used by the Unix shell.
Read more…
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
character(len=*), intent(in) :: pattern
Given pattern.
character(len=:), intent(out), allocatable :: list(:)
List of matching pathnames.
private subroutine glob_string(self, pattern, list)
Glob search (string output), finds all the pathnames matching a given pattern according to the rules used by the Unix shell.
Read more…
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: self
The string.
character(len=*), intent(in) :: pattern
Given pattern.
type(string), intent(out), allocatable :: list(:)
List of matching pathnames.
Call graph
glob calls glob_character, glob_string
glob_character calls glob
glob_string calls read_file, split
read_file calls chars, read_lines, upper
split calls partition, unique
partition calls raw
read_lines calls read_line
unique calls replace
read_line calls chars, upper
replace calls replace_one_occurrence
volatile_doctest calls glob