strjoin – StringiFor
strjoin Interface
3 statements
Source File
public interface strjoin
Calls
Contents
Module Procedures
strjoin_strings strjoin_characters strjoin_strings_array strjoin_characters_array
Module Procedures
private pure function strjoin_strings(array, sep) result(join)
Return a string that is a join of an array of strings.
Read more…
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: array(1:)
Array to be joined.
character(kind=CK, len=*), intent(in), optional :: sep
Separator.
Return Value type(string)
The join of array.
private pure function strjoin_characters(array, sep, is_trim) result(join)
Return a string that is a join of an array of characters.
Read more…
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: array(1:)
Array to be joined.
character(kind=CK, len=*), intent(in), optional :: sep
Separator.
logical, intent(in), optional :: is_trim
Flag to setup trim character or not
Return Value type(string)
The join of array.
private pure function strjoin_strings_array(array, sep, is_col) result(join)
Return a string that is a join of columns or rows of an array of strings.
Read more…
Arguments
Type Intent Optional Attributes Name
class(string), intent(in) :: array(1:,1:)
Array to be joined.
character(kind=CK, len=*), intent(in), optional :: sep
Separator.
logical, intent(in), optional :: is_col
Direction: ‘columns’ if .true. or ‘rows’ if .false.
Return Value type(string), allocatable, (:)
The join of array.
private pure function strjoin_characters_array(array, sep, is_trim, is_col) result(join)
Return a string that is a join of columns or rows of an array of characters.
Read more…
Arguments
Type Intent Optional Attributes Name
character(kind=CK, len=*), intent(in) :: array(1:,1:)
Array to be joined.
character(kind=CK, len=*), intent(in), optional :: sep
Separator.
logical, intent(in), optional :: is_trim
Flag to setup trim character or not
logical, intent(in), optional :: is_col
Direction: ‘columns’ if .true. or ‘rows’ if .false.
Return Value type(string), allocatable, (:)
The join of array.
Call graph
strjoin calls strjoin_characters, strjoin_characters_array, strjoin_strings, strjoin_strings_array
strjoin_characters calls raw
strjoin_characters_array calls strjoin_characters
strjoin_strings calls raw
strjoin_strings_array calls strjoin_strings