volatile_doctest – StringiFor
volatile_doctest Program
9 statements
Source File
Uses
penf
stringifor_string_t
Calls
Variables
Type Attributes Name Initial
type(string) :: astring
logical :: test_passed(1)
Source Code
program volatile_doctest
use stringifor_string_t
 use penf
 type(string) :: astring
 logical :: test_passed(1)
 astring = 127_I1P
 test_passed(1) = astring%to_number(kind=1_I1P)==127_I1P
 print '(L1)', all(test_passed)
endprogram volatile_doctest
Call graph
volatile_doctest calls to_number
to_integer_i1p calls is_integer
to_integer_i2p calls is_integer
to_integer_i4p calls is_integer
to_integer_i8p calls is_integer
to_real_r4p calls is_real
to_real_r8p calls is_real