volatile_doctest – StringiFor
volatile_doctest Program
30 statements
Source File
Uses
stringifor_string_t
Calls
Contents
Variables
astring alist_str Nf files file_unit f ff test_passed
Source Code
volatile_doctest
Variables
Type Attributes Name Initial
type(string) :: astring
type(string), allocatable :: alist_str(:)
integer, parameter :: Nf = 5
character(len=14) :: files(1:Nf)
integer :: file_unit
integer :: f
integer :: ff
logical :: test_passed
Source Code
program volatile_doctest
use stringifor_string_t
 type(string) :: astring
 type(string), allocatable :: alist_str(:)
 integer, parameter :: Nf=5
 character(14) :: files(1:Nf)
 integer :: file_unit
 integer :: f
 integer :: ff
 logical :: test_passed
 do f=1, Nf
 files(f) = astring%tempname(prefix='foo-')
 open(newunit=file_unit, file=files(f))
 write(file_unit, *)f
 close(unit=file_unit)
 enddo
 call astring%glob(pattern='foo-*', list=alist_str)
 do f=1, Nf
 open(newunit=file_unit, file=files(f))
 close(unit=file_unit, status='delete')
 enddo
 test_passed = .false.
 outer_str: do f=1, size(alist_str, dim=1)
 do ff=1, Nf
 test_passed = alist_str(f) == files(ff)
 if (test_passed) cycle outer_str
 enddo
 enddo outer_str
 print '(L1)', test_passed
endprogram volatile_doctest
Call graph
volatile_doctest calls glob
glob calls glob_character, glob_string
glob_character calls glob
glob_string calls read_file, split
read_file calls chars, read_lines, upper
split calls partition, unique
partition calls raw
read_lines calls read_line
unique calls replace
read_line calls chars, upper
replace calls replace_one_occurrence