b64_encode_string – StringiFor
b64_encode_string Subroutine
Source File
private pure subroutine b64_encode_string(s, code)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: s
String to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded scalar.
Description
Encode scalar string to base64.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=I1P), public, allocatable :: nI1P(:)
One byte integer array containing n.
integer(kind=I4P), public :: padd
Number of padding characters ('=').
integer(kind=I4P), public :: BYCHS
Bytes of character string.
Source Code
  pure subroutine b64_encode_string(s, code)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Encode scalar string to base64.
  !---------------------------------------------------------------------------------------------------------------------------------
  character(*),                  intent(in)  :: s       !< String to be encoded.
  character(len=:), allocatable, intent(out) :: code    !< Encoded scalar.
  integer(I1P),     allocatable              :: nI1P(:) !< One byte integer array containing n.
  integer(I4P)                               :: padd    !< Number of padding characters ('=').
  integer(I4P)                               :: BYCHS   !< Bytes of character string.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  BYCHS = byte_size(s)
  allocate(nI1P(1:((BYCHS+2)/3)*3)) ; nI1P = 0_I1P
  code = repeat(' ',((BYCHS+2)/3)*4)
  nI1P = transfer(s,nI1P)
  padd = mod((BYCHS),3_I4P) ; if (padd>0_I4P) padd = 3_I4P - padd
  call encode_bits(bits=nI1P,padd=padd,code=code)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_encode_string
Call graph
b64_encode_string calls byte_size, encode_bits
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr
b64_encode_up calls b64_encode_string
b64_encode calls b64_encode_string
encode calls b64_encode
autotest calls b64_encode
test_driver calls autotest