b64_encode_up_a – StringiFor
b64_encode_up_a Subroutine
Source File
private pure subroutine b64_encode_up_a(up, code)
Arguments
Type Intent Optional Attributes Name
class(*), intent(in) :: up(1:)
Unlimited polymorphic variable to be encoded.
character(len=:), intent(out), allocatable :: code
Encoded array.
Description
Encode an unlimited polymorphic array to base64.
Calls
Called By
Source Code
  pure subroutine b64_encode_up_a(up, code)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Encode an unlimited polymorphic array to base64.
  !---------------------------------------------------------------------------------------------------------------------------------
  class(*),                      intent(in)  :: up(1:) !< Unlimited polymorphic variable to be encoded.
  character(len=:), allocatable, intent(out) :: code   !< Encoded array.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  select type(up)
  type is(real(R8P))
    call b64_encode_R8_a(n=up,code=code)
  type is(real(R4P))
    call b64_encode_R4_a(n=up,code=code)
  type is(integer(I8P))
    call b64_encode_I8_a(n=up,code=code)
  type is(integer(I4P))
    call b64_encode_I4_a(n=up,code=code)
  type is(integer(I2P))
    call b64_encode_I2_a(n=up,code=code)
  type is(integer(I1P))
    call b64_encode_I1_a(n=up,code=code)
  type is(character(*))
    call b64_encode_string_a(s=up,code=code)
  endselect
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endsubroutine b64_encode_up_a
Call graph
b64_encode_up_a calls b64_encode_r8_a, b64_encode_string_a, b64_encode_i1_a, b64_encode_r4_a, b64_encode_i8_a, b64_encode_i4_a, b64_encode_i2_a
b64_encode_r8_a calls encode_bits
b64_encode_string_a calls encode_bits, byte_size
b64_encode_i1_a calls encode_bits
b64_encode_r4_a calls encode_bits
b64_encode_i8_a calls encode_bits
b64_encode_i4_a calls encode_bits
b64_encode_i2_a calls encode_bits
byte_size calls byte_size_i2p, byte_size_i1p, byte_size_r8p, byte_size_i8p, byte_size_i4p, byte_size_r4p, byte_size_chr
b64_encode_up calls b64_encode_up_a, b64_encode_up