str_a_R4P – StringiFor
str_a_R4P Function
Source File
private pure function str_a_R4P(n, no_sign, delimiters, compact) result(str)
Arguments
Type Intent Optional Attributes Name
real(kind=R4P), intent(in) :: n(:)
Real array to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
character(len=*), intent(in), optional :: delimiters(1:2)
Eventual delimiters of array values.
logical, intent(in), optional :: compact
Flag for compacting string encoding.
Return Value character(len=:), allocatable
Returned string containing input number.
Description
Convert real array to string.
Calls
Called By
Variables
Type Visibility Attributes Name Initial
character(len=DR4P), public :: strn
String containing of element of input array number.
integer, public :: i
Counter.
Source Code
  pure function str_a_R4P(n, no_sign, delimiters, compact) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert real array to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  real(R4P),    intent(in)           :: n(:)            !< Real array to be converted.
  logical,      intent(in), optional :: no_sign         !< Flag for leaving out the sign.
  character(*), intent(in), optional :: delimiters(1:2) !< Eventual delimiters of array values.
  logical,      intent(in), optional :: compact         !< Flag for *compacting* string encoding.
  character(len=:), allocatable      :: str             !< Returned string containing input number.
  character(DR4P)                    :: strn            !< String containing of element of input array number.
  integer                            :: i               !< Counter.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  str = ''
  do i=1,size(n)
    strn = str_R4P(no_sign=no_sign, compact=compact, n=n(i))
    str = str//','//trim(strn)
  enddo
  str = trim(str(2:))
  if (present(delimiters)) str = delimiters(1)//str//delimiters(2)
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_a_R4P
Call graph
str_a_r4p calls str_r4p
str_r4p calls compact_real_string
str calls str_a_r4p
bctor_r8p calls str
test_all calls str, bcton
string_assign_real_r16p calls str
bctor_r4p calls str
compact_real calls str
bctoi_i4p calls str
autotest calls str
string_assign_integer_i2p calls str
string_assign_real_r8p calls str
string_assign_real_r4p calls str
string_assign_integer_i4p calls str
bctoi_i8p calls str
string_assign_integer_i8p calls str
bctor_r16p calls str
bctoi_i1p calls str
bctoi_i2p calls str
string_assign_integer_i1p calls str
bcton calls bctor_r8p, bctor_r4p, bctoi_i4p, bctoi_i8p, bctoi_i1p, bctoi_i2p
test_driver calls autotest