str_I8P – StringiFor
str_I8P Function
Source File
private elemental function str_I8P(n, no_sign) result(str)
Arguments
Type Intent Optional Attributes Name
integer(kind=I8P), intent(in) :: n
Integer to be converted.
logical, intent(in), optional :: no_sign
Flag for leaving out the sign.
Return Value character(len=DI8P)
Returned string containing input number plus padding zeros.
Description
Convert integer to string.
Called By
Source Code
  elemental function str_I8P(n, no_sign) result(str)
  !---------------------------------------------------------------------------------------------------------------------------------
  !< Convert integer to string.
  !---------------------------------------------------------------------------------------------------------------------------------
  integer(I8P), intent(in)           :: n       !< Integer to be converted.
  logical,      intent(in), optional :: no_sign !< Flag for leaving out the sign.
  character(DI8P)                    :: str     !< Returned string containing input number plus padding zeros.
  !---------------------------------------------------------------------------------------------------------------------------------
  !---------------------------------------------------------------------------------------------------------------------------------
  write(str, FI8P) n                ! Casting of n to string.
  str = adjustl(trim(str))          ! Removing white spaces.
  if (n>=0_I8P) str='+'//trim(str)  ! Prefixing plus if n>0.
  if (present(no_sign)) str=str(2:) ! Leaving out the sign.
  return
  !---------------------------------------------------------------------------------------------------------------------------------
  endfunction str_I8P
Call graph
str_a_i8p calls str_i8p
str calls str_i8p, str_a_i8p
bctor_r4p calls str
bctoi_i8p calls str
bctor_r16p calls str
bctoi_i1p calls str
bctoi_i4p calls str
bctoi_i2p calls str
bctor_r8p calls str
bcton calls bctor_r4p, bctoi_i8p, bctoi_i1p, bctoi_i4p, bctoi_i2p, bctor_r8p